### ISSUE TITLE
Problems in compilation and execution of the PlanesDeltaAngle functor

### ISSUE THREAD

**Issue by Hiigaran** [MultithreadCorner/Hydra#112]
Good morning,

I had some error messages in compilation when I tried to use the functor PlanesDeltaAngle.

I tried to fix the problem by changing the signature of the functor. (see attached file).

Kind regards

Hiigaran

[PlanesDeltaAngle.zip](https://github.com/MultithreadCorner/Hydra/files/8044107/PlanesDeltaAngle.zip)

**Comment by Hiigaran** [comment]
[PlanesDeltaAngle.zip](https://github.com/MultithreadCorner/Hydra/files/8044101/PlanesDeltaAngle.zip)

**Comment by dbrundu** [comment]
Hi Hiigaran,

the problem is due to the fact that this functor has not been updated to the new function-call features of Hydra 3. In fact, the class is not templated with the usual `ArgType` and `Signature` typenames:

https://github.com/MultithreadCorner/Hydra/blob/50c701be3ebe9cf9f28fa9d69f6b32f5120d0d45/hydra/functions/PlanesDeltaAngle.h#L56

In principle the class can be templated with `template<typename ArgType, typename Signature=double(ArgType)>`,  but there are two overloads of the method `Evaluate()` with different signatures, so we need to check if both are needed.

**Comment by AAAlvesJr** [comment]
Hello, sorry for the delay. I will correct this ahead Hydra 4 release.
